CREATE TABLE test_jira_instance (
  instance_id   NUMBER(10)          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  instance_key  VARCHAR2(50 BYTE)   NOT NULL,
  base_url      VARCHAR2(500 BYTE)  NOT NULL,
  auth_type     VARCHAR2(10 BYTE)   DEFAULT 'PAT' NOT NULL,
  secret_ref    VARCHAR2(200 BYTE)  NOT NULL,
  is_active     CHAR(1 BYTE)        DEFAULT 'Y' NOT NULL,
  created_at    TIMESTAMP           DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  updated_at    TIMESTAMP           DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  CONSTRAINT test_pk_jira_instance      PRIMARY KEY (instance_id),
  CONSTRAINT test_uq_jira_instance_key  UNIQUE (instance_key),
  CONSTRAINT test_ck_jira_instance_auth CHECK (auth_type IN ('PAT','BASIC')),
  CONSTRAINT test_ck_jira_instance_act  CHECK (is_active IN ('Y','N'))
);

CREATE TABLE test_jira_project (
  project_id       NUMBER(10)         GENERATED BY DEFAULT ON NULL AS IDENTITY,
  instance_id      NUMBER(10)         NOT NULL,
  jira_project_id  VARCHAR2(50 BYTE)  NOT NULL,
  project_key      VARCHAR2(50 BYTE)  NOT NULL,
  name             VARCHAR2(255 BYTE),
  is_enabled       CHAR(1 BYTE)       DEFAULT 'N' NOT NULL,
  created_at       TIMESTAMP          DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  updated_at       TIMESTAMP          DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  CONSTRAINT test_pk_jira_project      PRIMARY KEY (project_id),
  CONSTRAINT test_uq_jira_project      UNIQUE (instance_id, jira_project_id),
  CONSTRAINT test_fk_jira_project_inst FOREIGN KEY (instance_id)
                                  REFERENCES test_jira_instance (instance_id),
  CONSTRAINT test_ck_jira_project_en   CHECK (is_enabled IN ('Y','N'))
);

CREATE INDEX test_ix_jira_project_key ON test_jira_project (instance_id, project_key);

CREATE TABLE test_jira_field (
  field_pk      NUMBER(10)          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  instance_id   NUMBER(10)          NOT NULL,
  field_id      VARCHAR2(100 BYTE)  NOT NULL,   -- 'customfield_10001' | 'status'
  field_name    VARCHAR2(255 BYTE)  NOT NULL,
  is_custom     CHAR(1 BYTE)        NOT NULL,
  schema_type   VARCHAR2(50 BYTE),              -- Jira schema.type
  schema_items  VARCHAR2(50 BYTE),              -- array일 때 원소 타입
  custom_type   VARCHAR2(200 BYTE),             -- 커스텀 필드 플러그인 키
  value_kind    VARCHAR2(10 BYTE)   NOT NULL,   -- NUM | STR | DATE | MULTI
  storage_kind  VARCHAR2(10 BYTE)   DEFAULT 'EAV' NOT NULL,
  column_name   VARCHAR2(30 BYTE),              -- COLUMN일 때 그룹핑에 쓸 컬럼
  label_column_name VARCHAR2(30 BYTE),          -- 표시용 컬럼 (없으면 column_name 그대로)
  is_dimension  CHAR(1 BYTE)        DEFAULT 'Y' NOT NULL,
  is_measure    CHAR(1 BYTE)        DEFAULT 'N' NOT NULL,
  first_seen_at TIMESTAMP           DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  last_seen_at  TIMESTAMP           DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  CONSTRAINT test_pk_jira_field       PRIMARY KEY (field_pk),
  CONSTRAINT test_uq_jira_field       UNIQUE (instance_id, field_id),
  CONSTRAINT test_fk_jira_field_inst  FOREIGN KEY (instance_id)
                                 REFERENCES test_jira_instance (instance_id),
  CONSTRAINT test_ck_jira_field_cst   CHECK (is_custom IN ('Y','N')),
  CONSTRAINT test_ck_jira_field_vk    CHECK (value_kind  IN ('NUM','STR','DATE','MULTI')),
  CONSTRAINT test_ck_jira_field_sk    CHECK (storage_kind IN ('COLUMN','EAV')),
  CONSTRAINT test_ck_jira_field_col   CHECK (
      (storage_kind = 'COLUMN' AND column_name IS NOT NULL)
   OR (storage_kind = 'EAV'    AND column_name IS NULL)),
  CONSTRAINT test_ck_jira_field_lbl   CHECK (label_column_name IS NULL
                                     OR column_name IS NOT NULL),
  CONSTRAINT test_ck_jira_field_dim   CHECK (is_dimension IN ('Y','N')),
  CONSTRAINT test_ck_jira_field_msr   CHECK (is_measure   IN ('Y','N'))
);

-- 인스턴스 간 자동 추천용 (이름+타입 일치 탐색)
CREATE INDEX test_ix_jira_field_unify ON test_jira_field (field_name, value_kind);

CREATE TABLE test_jira_project_field (
  project_id           NUMBER(10) NOT NULL,
  field_pk             NUMBER(10) NOT NULL,
  issue_count          NUMBER(10) DEFAULT 0 NOT NULL,
  distinct_value_count NUMBER(10) DEFAULT 0 NOT NULL,
  last_profiled_at     TIMESTAMP,
  CONSTRAINT test_pk_jira_project_field PRIMARY KEY (project_id, field_pk),
  CONSTRAINT test_fk_jpf_project FOREIGN KEY (project_id) REFERENCES test_jira_project (project_id),
  CONSTRAINT test_fk_jpf_field   FOREIGN KEY (field_pk)   REFERENCES test_jira_field   (field_pk)
);

CREATE INDEX test_ix_jpf_field ON test_jira_project_field (field_pk);
