CREATE TABLE test_unified_field (
  unified_field_id NUMBER(10)         GENERATED BY DEFAULT ON NULL AS IDENTITY,
  name             VARCHAR2(255 BYTE) NOT NULL,
  value_kind       VARCHAR2(10 BYTE)  NOT NULL,
  created_at       TIMESTAMP          DEFAULT (SYS_EXTRACT_UTC(SYSTIMESTAMP) + INTERVAL '9' HOUR) NOT NULL,
  CONSTRAINT test_pk_unified_field    PRIMARY KEY (unified_field_id),
  CONSTRAINT test_uq_unified_field    UNIQUE (name),
  CONSTRAINT test_ck_unified_field_vk CHECK (value_kind IN ('NUM','STR','DATE','MULTI'))
);

CREATE TABLE test_unified_field_member (
  unified_field_id NUMBER(10) NOT NULL,
  field_pk         NUMBER(10) NOT NULL,
  CONSTRAINT test_pk_ufm       PRIMARY KEY (unified_field_id, field_pk),
  CONSTRAINT test_uq_ufm_field UNIQUE (field_pk),
  CONSTRAINT test_fk_ufm_uf    FOREIGN KEY (unified_field_id)
                          REFERENCES test_unified_field (unified_field_id),
  CONSTRAINT test_fk_ufm_field FOREIGN KEY (field_pk) REFERENCES test_jira_field (field_pk)
);

CREATE TABLE test_unified_value (
  unified_value_id NUMBER(10)          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  unified_field_id NUMBER(10)          NOT NULL,
  canonical_value  VARCHAR2(1000 BYTE) NOT NULL,
  CONSTRAINT test_pk_unified_value  PRIMARY KEY (unified_value_id),
  CONSTRAINT test_uq_unified_value  UNIQUE (unified_field_id, canonical_value),
  CONSTRAINT test_uq_unified_value2 UNIQUE (unified_field_id, unified_value_id),
  CONSTRAINT test_fk_uv_uf          FOREIGN KEY (unified_field_id)
                               REFERENCES test_unified_field (unified_field_id)
);

CREATE TABLE test_unified_value_member (
  unified_field_id NUMBER(10)          NOT NULL,
  unified_value_id NUMBER(10)          NOT NULL,
  field_pk         NUMBER(10)          NOT NULL,
  raw_value        VARCHAR2(1000 BYTE) NOT NULL,
  CONSTRAINT test_pk_uvm        PRIMARY KEY (field_pk, raw_value),
  CONSTRAINT test_fk_uvm_value  FOREIGN KEY (unified_field_id, unified_value_id)
                           REFERENCES test_unified_value (unified_field_id, unified_value_id),
  CONSTRAINT test_fk_uvm_member FOREIGN KEY (unified_field_id, field_pk)
                           REFERENCES test_unified_field_member (unified_field_id, field_pk)
);

CREATE INDEX test_ix_uvm_uv ON test_unified_value_member (unified_value_id);

CREATE OR REPLACE VIEW test_v_unify_candidate AS
SELECT a.field_pk    AS field_pk_a,
       a.instance_id AS instance_id_a,
       b.field_pk    AS field_pk_b,
       b.instance_id AS instance_id_b,
       a.field_name,
       a.value_kind
FROM   test_jira_field a
JOIN   test_jira_field b
       ON  b.field_name  = a.field_name
       AND b.value_kind  = a.value_kind
       AND b.instance_id > a.instance_id          -- 쌍을 한 방향으로만
WHERE  a.is_custom = 'Y'
AND    b.is_custom = 'Y'
AND    NOT EXISTS (SELECT 1 FROM test_unified_field_member m WHERE m.field_pk = a.field_pk)
AND    NOT EXISTS (SELECT 1 FROM test_unified_field_member m WHERE m.field_pk = b.field_pk);
