CREATE TABLE test_issue_changelog (
  changelog_id        NUMBER(14)          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  issue_id            NUMBER(12)          NOT NULL,
  jira_history_id     VARCHAR2(50 BYTE)   NOT NULL,
  item_seq            NUMBER(4)           DEFAULT 0 NOT NULL,
  author_user_key     VARCHAR2(255 BYTE),
  author_display_name VARCHAR2(255 BYTE),
  changed_at          TIMESTAMP           NOT NULL,   -- KST
  field_pk            NUMBER(10),                     -- 카탈로그에 없는 필드면 NULL
  field_name          VARCHAR2(255 BYTE)  NOT NULL,   -- changelog 원본 field 문자열
  from_id             VARCHAR2(255 BYTE),
  from_str            VARCHAR2(4000 BYTE),
  to_id               VARCHAR2(255 BYTE),
  to_str              VARCHAR2(4000 BYTE),
  CONSTRAINT test_pk_changelog       PRIMARY KEY (changelog_id),
  CONSTRAINT test_uq_changelog       UNIQUE (issue_id, jira_history_id, item_seq),
  CONSTRAINT test_fk_changelog_issue FOREIGN KEY (issue_id) REFERENCES test_jira_issue (issue_id),
  CONSTRAINT test_fk_changelog_field FOREIGN KEY (field_pk) REFERENCES test_jira_field (field_pk)
);

CREATE INDEX test_ix_changelog_issue ON test_issue_changelog (issue_id, changed_at);
CREATE INDEX test_ix_changelog_field ON test_issue_changelog (field_pk, changed_at);

CREATE TABLE test_issue_field_history (
  issue_id   NUMBER(12)          NOT NULL,
  field_pk   NUMBER(10)          NOT NULL,
  valid_from TIMESTAMP           NOT NULL,   -- KST, 경계 포함
  valid_to   TIMESTAMP           DEFAULT TIMESTAMP '9999-12-31 00:00:00' NOT NULL,
  val_str    VARCHAR2(1000 BYTE),
  val_id     VARCHAR2(100 BYTE),
  CONSTRAINT test_pk_ifh       PRIMARY KEY (issue_id, field_pk, valid_from),
  CONSTRAINT test_fk_ifh_issue FOREIGN KEY (issue_id) REFERENCES test_jira_issue (issue_id),
  CONSTRAINT test_fk_ifh_field FOREIGN KEY (field_pk) REFERENCES test_jira_field (field_pk),
  CONSTRAINT test_ck_ifh_range CHECK (valid_from < valid_to)
);

CREATE INDEX test_ix_ifh_scan ON test_issue_field_history
  (field_pk, valid_from, valid_to, issue_id);
