CREATE TABLE test_sync_watermark (
  project_id             NUMBER(10)        NOT NULL,
  last_synced_updated_at TIMESTAMP,                    -- UTC
  last_run_at            TIMESTAMP,
  last_status            VARCHAR2(20 BYTE),
  full_resync_requested  CHAR(1 BYTE) DEFAULT 'N' NOT NULL,
  CONSTRAINT test_pk_sync_watermark PRIMARY KEY (project_id),
  CONSTRAINT test_fk_sw_project     FOREIGN KEY (project_id)
                               REFERENCES test_jira_project (project_id),
  CONSTRAINT test_ck_sw_status      CHECK (last_status IN ('SUCCESS','FAILED','RUNNING')),
  CONSTRAINT test_ck_sw_full        CHECK (full_resync_requested IN ('Y','N'))
);

CREATE TABLE test_sync_run (
  run_id          NUMBER(12)         GENERATED BY DEFAULT ON NULL AS IDENTITY,
  instance_id     NUMBER(10)         NOT NULL,
  project_id      NUMBER(10),                     -- 카탈로그 동기화는 NULL
  step            VARCHAR2(30 BYTE)  NOT NULL,
  started_at      TIMESTAMP          DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,
  finished_at     TIMESTAMP,
  status          VARCHAR2(20 BYTE)  DEFAULT 'RUNNING' NOT NULL,
  issues_fetched  NUMBER(10)         DEFAULT 0 NOT NULL,
  issues_upserted NUMBER(10)         DEFAULT 0 NOT NULL,
  error_msg       VARCHAR2(4000 BYTE),
  CONSTRAINT test_pk_sync_run   PRIMARY KEY (run_id),
  CONSTRAINT test_fk_sr_inst    FOREIGN KEY (instance_id) REFERENCES test_jira_instance (instance_id),
  CONSTRAINT test_fk_sr_proj    FOREIGN KEY (project_id)  REFERENCES test_jira_project  (project_id),
  CONSTRAINT test_ck_sr_status  CHECK (status IN ('RUNNING','SUCCESS','FAILED')),
  CONSTRAINT test_ck_sr_step    CHECK (step IN
                           ('CATALOG','ISSUES','HISTORY','FIRST_DONE',
                            'PROFILE','DETECT_DELETED'))
);

CREATE INDEX test_ix_sync_run_recent ON test_sync_run (project_id, started_at DESC);
